DATASET:
    upsamplingFactor: 4 # from heatmaps (64 x 64) to RGB (256 x 256)
    duration: 1800
    heatmapSize: 64
    imgSize: 256
    rangeSize: 64
    azimuthSize: 64
    numKeypoints: 14
    numFrames: 16 # num of chirps in one frame you want to use as an input
    numGroupFrames: 48 # set -1 if using single frame
    numChirps: 16
    log: False
    stdmean: True
    #useVelocity: False
    #mode: "multiFramesChirps"
    dataDir: './data/20211106_Pad_CltRm_RDA' # the first dir will be the test/val set
    pretrainDir: './logs/unet_df_prgcn/' # only for stgcn2_stage2
    testName: [1, 3, 21, 25, 44, 62, 82, 104]
    valName: [1, 3, 21, 25, 44, 62, 82, 104]
    trainName: [2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,26,27,28,29,30,31,32,33,34,35,36,
                37,38,39,40,41,42,43,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,63,64,65,66,67,68,69,
                70,71,72,73,74,75,76,77,78,79,80,81,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,
                102,103,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120]
    idxToJoints:
        ["R_Hip", "R_Knee", "R_Ankle", "L_Hip", "L_Knee", 
         "L_Ankle", "Neck", "Head", "L_Shoulder", "L_Elbow", 
         "L_Wrist", "R_Shoulder", "R_Elbow", "R_Wrist"]
MODEL:
    numFilters: 48
    frontModel: "stgcn3_stage2"
    backbone: "resnet"
    chirpModel: "mnet"
    type: "justregress"
    gcnType: "coord_var" #"conf" or "coord" or "coord_var"
TRAINING:
    batchSize: 80 #40
    epochs: 200
    lr: 0.0001
    warmupEpoch: -1
    warmupGrowth: 1.005
    lrDecay: 0.999
    optimizer: "adam"
    metric: "APCK"
TEST:
    batchSize: 80 #40
    plotImgDir: "20211106"
    outputName: "STGCN3_stage2"
SETUP:
    numWorkers: 4
