DATASET:
    upsamplingFactor: 8 # from heatmaps (64 x 64) to RGB (512 x 512)
    duration: 1800
    heatmapSize: 64
    imgSize: 512
    rangeSize: 64
    azimuthSize: 64
    numKeypoints: 16
    numFrames: 16
    numGroupFrames: -1 # set -1 if using single frame
    mode: "multiChirps"
    dataDir: "./data/20210728_Pad"
    testName: ["single_13"]
    valName: ["single_13"]
    trainName: ['single_14', 'single_15', 'single_16', 'single_17', 'single_18', 'single_19', 'single_20', 'single_21', 'single_22', 'single_23', 'single_24']
MODEL:
    numFilters: 32
    frontModel: "spatial4"
TRAINING:
    batchSize: 8
    epochs: 200
    lr: 0.01
    warmupEpoch: -1
    warmupGrowth: 1.005
    lrDecay: 0.9995
    optimizer: "sgd"
LOGGER:
    idxToJoints:
        ["RightAnkle", "RightKnee", "RightHip", "LeftHip", "LeftKnee", 
         "LeftAnkle", "Pelvis", "Chest", "Neck", "head", 
         "RightWrist", "RightElbow", "RightShoulder", "LeftShoulder", "LeftElbow", "LeftWrist"]
    plotImgDir: "20210728"
    intervalEval: 5
SETUP:
    numWorkers: 24
