DATASET:
    upsamplingFactor: 4 # from heatmaps (64 x 64) to RGB (256 x 256)
    duration: 1800
    heatmapSize: 64
    imgSize: 256
    rangeSize: 64
    azimuthSize: 64
    numKeypoints: 14
    numFrames: 16 # num of chirps in one frame you want to use as an input
    numGroupFrames: 24 # set -1 if using single frame
    numChirps: 16
    log: False
    stdmean: True
    useVelocity: False
    mode: "multiFramesChirps"
    dataDir: ['./data/20211106_Pad_CltRm_RDA'] # the first dir will be the test/val set
    testName: [["single_1", "single_3","single_21","single_25","single_44","single_62","single_82","single_104"]] #"single_45"
    valName: [["single_1", "single_3","single_21","single_25","single_44","single_62","single_82","single_104"]]
    trainName: [["single_2","single_4","single_5","single_6",
                "single_7","single_8","single_9","single_10","single_11","single_12",
                "single_13","single_14","single_15","single_16","single_17","single_18",
                "single_19","single_20","single_22","single_23","single_24",
                "single_26","single_27","single_28","single_29","single_30",
                "single_31","single_32","single_33","single_34","single_35","single_36",
                "single_37","single_38","single_39","single_40","single_41","single_42",
                "single_43","single_46","single_47","single_48",
                "single_49","single_50","single_51","single_52","single_53","single_54",
                "single_55","single_56","single_57","single_58","single_59","single_60",
                "single_61","single_63","single_64","single_65","single_66",
                "single_67","single_68","single_69","single_70","single_71","single_72",
                "single_73","single_74","single_75","single_76","single_77","single_78",
                "single_79","single_80","single_81","single_84",
                "single_85","single_86","single_87","single_88","single_89","single_90",
                "single_91","single_92","single_93","single_94","single_95","single_96",
                "single_97","single_98","single_99","single_100","single_101","single_102",
                "single_103","single_105","single_106","single_107","single_108",
                "single_109","single_110","single_111","single_112","single_113","single_114",
                "single_115","single_116","single_117","single_118","single_119","single_120",
                ]]
MODEL:
    numFilters: 48
    frontModel: "temporal3"
    backbone: "resnet"
    chirpModel: "mnet"
    type: "heatmap"
    gcnType: "None"
TRAINING:
    batchSize: 20
    epochs: 200
    lr: 0.0001
    warmupEpoch: -1
    warmupGrowth: 1.005
    lrDecay: 0.999
    optimizer: "adam"
    metric: "APCK" #"l2norm_PCK"
LOGGER:
    idxToJoints:
        ["R_Hip", "R_Knee", "R_Ankle", "L_Hip", "L_Knee", 
         "L_Ankle", "Neck", "Head", "L_Shoulder", "L_Elbow", 
         "L_Wrist", "R_Shoulder", "R_Elbow", "R_Wrist"]
    plotImgDir: "20211106"
    intervalEval: 5
SETUP:
    numWorkers: 4
