DATASET:
    upsamplingFactor: 4 # from heatmaps (64 x 64) to RGB (512 x 512)
    duration: 1800
    heatmapSize: 128
    imgSize: 512
    rangeSize: 128
    azimuthSize: 128
    numKeypoints: 16
    numFrames: 8 # num of chirps in one frame you want to use as an input
    numGroupFrames: 20 # set -1 if using single frame
    numChirps: 16
    log: False
    stdmean: True
    mode: "multiFramesChirps"
    dataDir: ['./data/20211008_Pad_CltRm'] # the first dir will be the test/val set
    testName: [["single_5"]]
    valName: [["single_5"]]
    trainName: [['single_2', 'single_3', 'single_4', 'single_1', 'single_6', 'single_7', 'single_8', 'single_9', 'single_10', 'single_11', 'single_12', 'single_13',
                 'single_14', 'single_15']]
MODEL:
    numFilters: 32
    frontModel: "temporal3"
    backbone: "resnet"
    chirpModel: "mnet"
    type: "heatmapMSE"
TRAINING:
    batchSize: 8
    epochs: 200
    lr: 0.01
    warmupEpoch: 1
    warmupGrowth: 1.005
    lrDecay: 0.9995
    optimizer: "sgd"
    metric: "l2norm"
LOGGER:
    idxToJoints:
        ["RightAnkle", "RightKnee", "RightHip", "LeftHip", "LeftKnee", 
         "LeftAnkle", "Pelvis", "Chest", "Neck", "head", 
         "RightWrist", "RightElbow", "RightShoulder", "LeftShoulder", "LeftElbow", "LeftWrist"]
    plotImgDir: "20211008"
    intervalEval: 5
SETUP:
    numWorkers: 6
