DATASET:
    upsamplingFactor: 8 # from heatmaps (64 x 64) to RGB (512 x 512)
    heatmapSize: 64
    imgSize: 512
    numKeypoints: 17
    mode: "multiChirps"
    numFrames: 16
    duration: 1800
    rangeSize: 64
    azimuthSize: 8
MODEL:
    numFilters: 16
LOGGER:
    idxToJoints:
        ["nose", "left_eye", "right_eye", "left_ear",
         "right_ear", "left_shoulder", "right_shoulder", "left_elbow",
         "right_elbow", "left_wrist", "right_wrist", "left_hip",
         "right_hip", "left_knee", "right_knee", "left_ankle",
         "right_ankle"]
    intervalEval: 5