DATASET:
    upsamplingFactor: 4 # from heatmaps (64 x 64) to RGB (256 x 256)
    duration: 1800
    heatmapSize: 64
    imgSize: 256
    rangeSize: 64
    azimuthSize: 64
    numKeypoints: 14
    numFrames: 16 # num of chirps in one frame you want to use as an input
    numGroupFrames: 24 # set -1 if using single frame
    numChirps: 16
    log: False
    stdmean: True
    useVelocity: False
    mode: "multiFramesChirps"
    dataDir: ['./data/20210916_Pad_CltRm_RDA'] # the first dir will be the test/val set
    testName: [["single_5"]]
    valName: [["single_5"]]
    trainName: [['single_2', 'single_3', 'single_4', 'single_1', 'single_6', 'single_7', 'single_8', 'single_9', 'single_10', 'single_11', 'single_12', 'single_13',
                 'single_14', 'single_15']]
MODEL:
    numFilters: 48
    frontModel: "temporal5"
    backbone: "resnet"
    chirpModel: "mnet"
    type: "heatmap_heatmap"
    gcnType: "gcn1"
TRAINING:
    batchSize: 16
    epochs: 200
    lr: 0.0001
    warmupEpoch: -1
    warmupGrowth: 1.005
    lrDecay: 0.999
    optimizer: "adam"
    metric: "l2norm_PCK"
LOGGER:
    idxToJoints:
        ["R_Hip", "R_Knee", "R_Ankle", "L_Hip", "L_Knee", 
         "L_Ankle", "Neck", "Head", "L_Shoulder", "L_Elbow", 
         "L_Wrist", "R_Shoulder", "R_Elbow", "R_Wrist"]
    plotImgDir: "20210916"
    intervalEval: 5
SETUP:
    numWorkers: 4
